### ISSUE TITLE
Add admin rights

### ISSUE THREAD

**Issue by mareksabo** [pkajaba/Recommender-Systems-Project#6]
App should have gem [rolify](https://github.com/RolifyCommunity/rolify) and [cancancan](https://github.com/CanCanCommunity/cancancan). No need for it now, maybe later.

**Comment by pkajaba** [comment]
@MartinMlynarik should have it implemented, right?

**Comment by MartinMlynarik** [comment]
nope :), but i think there is no need for it bacuse we are not planning on upadting/editig/deleting jokes/categories

**Comment by mareksabo** [comment]
^
